Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	config.vm.synced_folder ".", "/vagrant_data"

	# Máquina Master
	config.vm.define "antthomaS" do |control|
	control.vm.hostname = "antthomaS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
	control.vm.provision "shell", path: "scripts/server.sh"
	end

	# Máquina Worker
	config.vm.define "antthomaSW" do |control|
	control.vm.hostname = "antthomaSW"
	control.vm.network "private_network", ip: "192.168.56.111"
	control.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
	control.vm.provision "shell", path: "scripts/worker.sh"
	end
end